esphome:
  name: desk-buddy-esp-s3-box-3
  friendly_name: Desk Buddy
  includes:
    - Draw.h
    - DeskBuddyState.h
    - EyeAnimator.h
    - EyeAnimator.cpp
    - EyeRenderer.h
    - EyeRenderer.cpp
  on_boot:
    priority: -100
    then:
      - delay: 1s
      - lambda: 'DeskBuddyState::getInstance().init_in_progress = false;'
      - script.execute: neutral_animation
      - display.page.show: eye_page

esp32:
  board: esp32s3box
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

psram:
  mode: octal
  speed: 80MHz

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

api:

logger:
  level: INFO

spi:
  - id: spi_bus
    clk_pin: 7
    mosi_pin: 6

output:
  - platform: ledc
    pin: GPIO47
    id: backlight_output

light:
  - platform: monochromatic
    id: led
    name: LCD Backlight
    entity_category: config
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 50ms

i2c:
  scl: GPIO18
  sda: GPIO8

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin:
      number: GPIO45
      ignore_strapping_warning: true
    i2s_bclk_pin: GPIO17
    i2s_mclk_pin: GPIO2

audio_adc:
  - platform: es7210
    id: es7210_adc
    bits_per_sample: 16bit
    sample_rate: 16000

microphone:
  - platform: i2s_audio
    id: box_mic
    sample_rate: 16000
    i2s_din_pin: GPIO16
    bits_per_sample: 16bit
    adc_type: external

sensor:
  - platform: sound_level
    id: buddy_ears
    microphone: box_mic
    passive: false
    measurement_duration: 200ms
    rms:
      id: sound_rms
      name: "Buddy Average Volume"
      internal: true
    peak:
      id: sound_peak
      name: "Buddy Peak Volume"
      internal: true

binary_sensor:
  - platform: template
    id: is_loud_noise
    lambda: 'return id(sound_peak).state > -16.0;'
    on_press:
      then:
        - script.execute: scared_reaction


number:
  - platform: template
    name: "Happiness Level"
    id: happiness_meter
    optimistic: true
    min_value: -100
    max_value: 100
    step: 1
    initial_value: 0
    icon: "mdi:emoticon-happy-outline"

interval:
  - interval: 40ms
    then:
      - if:
          condition:
            lambda: 'return !DeskBuddyState::getInstance().init_in_progress;'
          then:
            - component.update: s3_box_lcd
  - interval: 1h
    then:
      - lambda: |-
          auto& state = DeskBuddyState::getInstance();
          if (state.happiness_level > 0) {
            state.addHappiness(-1);
          } else if (state.happiness_level < 0) {
            state.addHappiness(1);
          }
          id(happiness_meter).publish_state(state.happiness_level);

script:
  - id: neutral_animation
    mode: parallel
    then:
      - while:
          condition:
            lambda: 'return true;'
          then:
            - lambda: 'EyeAnimator::performRandomAction();'
            - delay: 2s

  - id: eye_animation_blink
    mode: restart
    then:
      - lambda: 'EyeAnimator::performBlink();'

  - id: pet_interaction
    mode: restart
    then:
      - lambda: 'DeskBuddyState::getInstance().is_petted = true;'
      - component.update: s3_box_lcd
      - delay: 2s
      - lambda: 'DeskBuddyState::getInstance().is_petted = false;'
      - component.update: s3_box_lcd

  - id: scared_reaction
    mode: restart
    then:
      - lambda: |-
          EyeAnimator::handleScaredReaction();
          id(happiness_meter).publish_state(DeskBuddyState::getInstance().happiness_level);
      - component.update: s3_box_lcd
      - delay: 2s
      - lambda: 'DeskBuddyState::getInstance().is_scared = false;'
      - component.update: s3_box_lcd

touchscreen:
  platform: gt911
  id: s3_box_touch
  address: 0x5D
  interrupt_pin:
    number: GPIO3
    ignore_strapping_warning: true
  on_touch:
    then:
      - lambda: |-
          EyeAnimator::handlePetInteraction();
          id(happiness_meter).publish_state(DeskBuddyState::getInstance().happiness_level);
      - script.execute: pet_interaction

display:
  - platform: ili9xxx
    id: s3_box_lcd
    model: S3BOX
    invert_colors: false
    data_rate: 40MHz
    cs_pin: 5
    dc_pin: 4
    reset_pin:
      number: 48
      inverted: true
    update_interval: never
    pages:
      - id: eye_page
        lambda: 'EyeRenderer::render(it);'
